### PR TITLE
ebf 2.0

### PR DESCRIPTION
**Pull request by harishbansal**
New Commands
============
- Network Boot Image management
    ebf  <device name> netboot ls
    ebf  <device name> netboot mkdir
    ebf  <device name> netboot rm
    ebf  <device name> netboot upload
    ebf  <device name> netboot symlink
- SDCard Image management
    ebf  <device name> sdcard info
    ebf  <device name> sdcard side
    ebf  <device name> sdcard switch
    ebf  <device name> sdcard ls
    ebf  <device name> sdcard mkdir
    ebf  <device name> sdcard rm
    ebf  <device name> sdcard format
    ebf  <device name> sdcard partition
    ebf  <device name> sdcard backup
    ebf  <device name> sdcard flash
- EBF File Manager
    ebf <device name> bfc ls
- Serial support
    ebf  <device name> serial run
    ebf  <device name> serial download
    ebf  <device name> serial upload

Improvements
============
- Recursive directory upload/download support
    ebf  <device name> ssh upload
    ebf  <device name> ssh download
- contextual ebf command help

### CODE REVIEW

**Comment by atul-ts** [comment]
hi harish,
should it be called ebf cli instead of ebf?  Also update the readme  "test
the reference command line tool ('ebf')"
-Atul

**Comment by atul-ts** [comment]
update https://github.com/TimesysGit/board-farm-rest-api/tree/main/cli as
well

e..g  'ebf' cli is a tool .....

**Comment by harishbansal** [comment]
addreseed readme update in pull request - https://github.com/TimesysGit/board-farm-rest-api/pull/2

**Comment by harishbansal** [comment]
ebf-cli 1.0.1

New Commands
============
 - EBF File manager Commands
  - ebf fmanager ls
  - ebf fmanager mkdir
  - ebf fmanager rm 
  - ebf fmanager upload
  - ebf fmanager download
 - EBF Version Command
  - ebf Version
 - Zombie import-key 
  - ebf <device-name> ssh import-key
 - Netboot commands Additions
  - ebf <device-name> netboot transfer
  - ebf <device-name> netboot download
 - SDCard Commands
  - ebf <device-name> sdcard download
  - ebf <device-name> sdcard upload
 - USB Commands
  - ebf <device-name> usb info
  - ebf <device-name> usb  side
  - ebf <device-name> usb switch
  - ebf <device-name> usb ls
  - ebf <device-name> usb mkdir
  - ebf <device-name> usb rm
  - ebf <device-name> usb format
  - ebf <device-name> usb partition
  - ebf <device-name> usb backup
  - ebf <device-name> usb flash
  - ebf <device-name> usb download
  - ebf <device-name> usb upload
    
Existing Commands Syntax Updated
============
 - NAT Forwarding
  - ebf <device-name> portfw list
  - ebf bbb01 portfw add
  - ebf bbb01 portfw remove
    
EBF Commands Deleted
============
 - SSH Port Forwarding
  - ebf bbb01 portfw ssh list
  - ebf bbb01 portfw ssh add
  - ebf bbb01 portfw ssh remove
 - EBF FIle Manager
  - ebf <device name> bfc ls

**Pull request merged**
